### ISSUE TITLE
Flashing w/ maple bootloader

### ISSUE THREAD

**Issue by andree182** [SVentas/EvvGC-PLUS#2]
Hi,

fan of the code structure here... :)

A feature suggestion - make the code flashable using maple USB bootloader, like the 'original' evvgc code. I tried changing the link address + CORTEX_VTOR_INIT, but for whatever reason chibios does not seem to boot this way (the bootloader quickly flashes led; with evvgc it continues to the code after a second or two)...

I will probably try again later to make it work (as the uart1 method is needlessly complicated).

Cheers...

**Comment by andree182** [comment]
A patch to demonstrate what I had in mind... http://github.andree.sk/0001-nonfunctional-version-of-usb-boot-build.patch . Using it is then just 'make clean; make USB_BUILD=yes'

**Comment by SVentas** [comment]
Hi, **endree182**,
I think the described method should work just fine.

You also have to modifie the source because now it is impossible to reset the board and stay in bootloader after reset.
Will see what I can do with bootloader functionality,..
BTW I think this is an easy task. I hope You will solve it faster and submit a pull request :smiley:.

**Comment by andree182** [comment]
Hi!
Back here... I noticed you partially added the code to your repo:)

But anyhow, not even with the original maple bootloader (https://github.com/leaflabs/maple-bootloader) modified to 0x8004000 I can't seem to get the code to boot (neither original evvgc that works with evvgc bootloader, nor evvgc-plus though). Could you share how did you make it work?

**Comment by SVentas** [comment]
Hi, andree182,
I don't know why original maple bootloader does not work. I don't know why evvgc-maple bootloader does not work. Unfortunately right now it is not a problem I am interested in. You have to figure out yourself. It is obvious that evvgc-maple bootloader does not recognize user code. It stays in bootloader mode for ever.
I know that modified OpenPilot bootloader works fine. I also have my own USB bootloader based on mass storage device class and it works fine. STM32 demo bootloader works fine too. They all check for one single condition:
```c
// Test if user code is programmed starting from address 0x08004000
if (((*(__IO uint32_t*) APPLICATION_ADDR) & 0x2FFE0000 ) == 0x20000000)
{
  // Reset peripherals;
  // Jump to user application
}
```
This condition is true for EvvGC-PLUS binary.

**Comment by andree182** [comment]
Okay, no problem - I just want to know some functional configuration for now - I already almost killed the board by connecting LiPo and uart1 (it seems to be alive so far, fortunately). So I'd like to avoid the chances by using  (for now) any USB boot... Thanks! I will post back here, once I figure out the maple problem (or even close it, if other bootloader will work).

**Comment by SVentas** [comment]
I see :smiley:. By the way, it is very easy to fix the problem in maple bootloader (**main.c** mod.).
```c
/* wait for host to upload program or halt bootloader */
bool no_user_jump = !checkUserCode(USER_CODE_FLASH);
int delay_count = 0;

while ((delay_count++ < BOOTLOADER_WAIT)
        || no_user_jump) {

    strobePin(LED_BANK, LED, 1, BLINK_SLOW);

    if (dfuUploadStarted()) {
        dfuFinishUpload(); // systemHardReset from DFU once done
    }
}

if (checkUserCode(USER_CODE_FLASH)) {
    jumpToUser(USER_CODE_FLASH);
} else {
    // some sort of fault occurred, hard reset
    strobePin(LED_BANK, LED, 5, BLINK_FAST);
    systemHardReset();
}
```
Now it MUST work :smiley:

**Comment by andree182** [comment]
Success! :-)
Another issue was transfer size settings (wTransferSize => 0x0800), which caused corrupted uploads. Also I suspect the no_user_jump to pickup some noise from Pin... Anyhow, this all I can debug, if I have time, so... Thanks!
