### ISSUE TITLE
Firmware Toolchain

### ISSUE THREAD

**Issue by Manu3l0us** [SVentas/EvvGC-PLUS#6]
I haven't found any information about how to build the firmware. Which toolchain do you use? Sorry if I have overlooked the information.

**Comment by DroneBuster** [comment]
Personally im using PX4 build enviroment.

**Comment by Manu3l0us** [comment]
Ok, thank you. Will try to set that up tonight. Right now, I'm using Keil during my day job, but looking for something opensource for opensource development.
